config/routes.rb
OrnamentExample::Application.routes.draw do

  get '/' => 'styleguide#index', as: :styleguide
  get '/styleguide/:action' => 'styleguide'
  get '/test-404' => 'errors#404'
  
  # PWA Routes
  get '/site' => 'service_worker#webmanifest', format: :webmanifest, as: :webmanifest
  get '/service-worker' => 'service_worker#index', format: :js, as: :service_worker
  
  root :to => 'styleguide#index'

end

app/views/layouts/_analytics.html.erb
<%- ga_key = get_koi_site_setting("site.google_analytics.profile_id") -%>
<%- if ga_key -%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= ga_key -%>', 'auto');
    <%= yield :custom_ga -%>
    if(!Ornament.features.turbolinks) {
      ga('send', 'pageview');
    }
  </script>
<%- end -%>

app/views/layouts/_seo.html.erb
<%

  # Settings
  cache_version ||= "1"
  koi_settings ||= true
  disable_facebook ||= false
  disable_twitter ||= false
  disable_pwa_settings ||= false
  disable_structured_data ||= false

  # Defaults
  site_name ||= Rails.application.class.name.split("::").first.humanize
  meta_title ||= site_name
  meta_title_postfix ||= site_name
  meta_title_postfix_seperator ||= " - "
  meta_keywords ||= false
  meta_description ||= ""
  meta_image ||= false # "#{root_url}assets/share.png?v=#{cache_version}"
  meta_theme_colour ||= "#4b9dd0";

  # Facebook defaults
  facebook_app_id ||= false

  # Twitter defaults
  twitter_site ||= ""
  twitter_creator ||= ""

  # Inner settings
  facebook_crop = "1200x630#"
  twitter_crop = "800x418#"

  # Overrides via Koi Site Settings
  if defined?(Translation) && koi_settings

    # Get site settings
    koi_title = Translation.find_by_key('site.title').try(:value)
    koi_description = Translation.find_by_key('site.meta_description').try(:value)
    koi_keywords = Translation.find_by_key('site.meta_keywords').try(:value)

    # Clean inputs
    site_settings_title = clean_share_input(koi_title) if koi_title
    site_settings_description = clean_share_input(koi_description) if koi_description
    site_settings_keywords = clean_share_input(koi_keywords) if koi_keywords

    # Update values from koi settings
    meta_title = site_settings_title if !koi_title.blank?
    meta_title_postfix = meta_title if !koi_title.blank?
    meta_keywords = site_settings_keywords if !koi_keywords.blank?
    meta_description = site_settings_description if !koi_description.blank?
  end

  # 
  # Standard meta tags
  #
  # These come from:
  # 1. The Koi CRUD seo() helper
  # 2. The meta() view helper
  # 3. Fallback Koi site settings
  # 4. Fallback hardcoded values above
  #

  ### Page title

  # Try from koi setting
  if !seo("title").blank?
    meta_title = seo("title")

  # Try from meta(page_title)
  elsif content_for?(:meta_page_title)
    meta_title = yield(:meta_page_title)

  # Try from meta(title)
  elsif content_for?(:meta_title)
    meta_title = yield(:meta_title)

  # Try from generic :title yield
  elsif content_for?(:title)
    meta_title = yield(:title)
  end

  ### Meta Keywords

  # Try from koi setting
  if !seo("meta_description").blank?
    meta_description = clean_share_input(seo('meta_description'))
  
  # Try from meta(description)
  elsif content_for?(:meta_description) 
    meta_description = yield(:meta_description)
  end

  ### Meta Keywords

  # Try from koi setting
  if !seo("meta_keywords").blank?
    meta_keywords = clean_share_input(seo('meta_keywords'))

  # Try from meta(keywords)
  elsif content_for?(:meta_keywords)
    meta_keywords = yield(:meta_keywords)
  end

  ### Meta Image

  # Try from meta(image)
  meta_image = share_image(yield(:meta_image), facebook_crop) if content_for?(:meta_image)

  ## Theme colour
  meta_theme_colour = yield(:meta_theme_colour) if content_for?(:meta_theme_colour)

  #
  # Facebook meta overrides
  #
  # meta({
  #   facebook: {
  #     title: ""
  #   }
  # })
  #

  # Title
  facebook_title = meta_title
  facebook_title = yield(:meta_facebook_title) if content_for?(:meta_facebook_title)

  # Description
  facebook_description = meta_description
  facebook_description = yield(:meta_facebook_description) if content_for?(:meta_facebook_description)

  # URL
  facebook_url = request.original_url
  facebook_url = yield(:meta_facebook_url) if content_for?(:meta_facebook_url)

  # Image
  facebook_image = meta_image
  facebook_image = share_image(yield(:meta_facebook_image), facebook_crop) if content_for?(:meta_facebook_image)

  # Misc
  facebook_author = yield(:meta_facebook_author) if content_for?(:meta_facebook_author)
  facebook_publish_time = yield(:meta_facebook_publish_time) if content_for?(:meta_facebook_publish_time)

  #
  # Twitter meta overrides
  #
  # meta({
  #   twitter: {
  #     title: ""
  #   }
  # })
  #

  # Title
  twitter_title = meta_title
  twitter_title = yield(:meta_twitter_title) if content_for?(:meta_twitter_title)

  # Description
  twitter_description = meta_description
  twitter_description = yield(:meta_twitter_description) if content_for?(:meta_twitter_description)

  # Image
  twitter_image = meta_image
  twitter_image = share_image(yield(:meta_twitter_image), twitter_crop) if content_for?(:meta_twitter_image)
  twitter_image_alt = false
  twitter_image_alt = yield(:meta_twitter_image_alt) if content_for?(:meta_twitter_image_alt)

  # URL
  twitter_url = request.original_url
  twitter_url = yield(:meta_twitter_url) if content_for?(:meta_twitter_url)

  # Handle / Creator
  # These are usually site-wide set above by the defaults
  # Some cases might come where they may need to be unique
  twitter_site = yield(:meta_twitter_site) if content_for?(:meta_twitter_site)
  twitter_creator = yield(:meta_twitter_creator) if content_for?(:meta_twitter_creator)

  twitter_card_type = "summary"
  twitter_card_type = "summary_large_image" if twitter_image.present?
  twitter_card_type = yield(:meta_twitter_card) if content_for(:meta_twitter_card)
%>

  <title><%= meta_postfixer(meta_title, meta_title_postfix, meta_title_postfix_seperator) %></title>
<% if meta_description.present? %>
  <meta name="description" content="<%= raw meta_description %>" />
<% end %>
<% if meta_keywords %>
  <meta name="keywords" content="<%= raw meta_keywords %>">
<% end %>
<% if meta_image.present? %>
  <link rel="image_src" href="<%= meta_image %>" />
<% end %>
  <meta name="theme-color" content="<%= meta_theme_colour %>" />

<%# Facebook Output %>
<% unless disable_facebook %>
  <meta property="og:site_name" content="<%= site_name %>" />
  <meta property="og:title" content="<%= meta_postfixer(facebook_title, meta_title_postfix, meta_title_postfix_seperator) %>" />
  <meta property="og:url" content="<%= facebook_url %>" />
  <meta property="og:type" content="website" />

  <% if facebook_app_id %>
    <meta property="fb:app_id" content="<%= facebook_app_id %>" />
  <% end %>
  
  <% if facebook_description.present? %>
    <meta property="og:description" content="<%= raw facebook_description %>" />
  <% end %>
  <% if facebook_image.present? || content_for(:meta_facebook_disable_image) %>
    <meta property="og:image" content="<%= facebook_image %>" />
  <% end %>
  <% if facebook_author.present? %>
    <meta property="og:author" content="<%= facebook_author %>" />
  <% end %>
  <% if facebook_publish_time.present? %>
    <meta property="og:published_time" content="<%= facebook_publish_time %>" />
  <% end %>
<% end %>

<%# Twitter Output %>
<% unless disable_twitter %>
  <meta name="twitter:card" content="<%= twitter_card_type %>" />
  <% if twitter_site.present? %>
    <meta name="twitter:site" content="<%= twitter_site %>" />
  <% end %>
  <% if twitter_image.present? %>
    <meta name="twitter:image" content="<%= twitter_image %>" />
  <% end %>
  <% if twitter_image_alt.present? %>
    <meta name="twitter:image:alt" content="<%= twitter_image_alt %>" />
  <% end %>
  <% if twitter_creator.present? %>
    <meta name="twitter:creator" content="<%= twitter_creator %>" />
  <% end %>
  <meta name="twitter:title" content="<%= meta_postfixer(twitter_title, meta_title_postfix, meta_title_postfix_seperator) %>" />
  <meta name="twitter:url" content="<%= twitter_url %>" />
  <meta name="twitter:description" content="<%= raw twitter_description %>" />
<% end %>

<%# Application Icons %>
<% unless disable_pwa_settings %>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
  <link rel="manifest" href="<%= webmanifest_path(format: :webmanifest) %>" />
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="<%= meta_theme_colour %>" />
<% end %>

<%# Strucuted Data for enhanced search results %>
<%# Docs - https://developers.google.com/search/docs/guides/enhance-site %>
<%# Testing tool - https://search.google.com/structured-data/testing-tool %>
<% unless disable_structured_data %>
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    <% if content_for?(:structured_data) %>
      <%= yield :structured_data %>
    <% else %>
      "@type": "Organization",
      "url": "<%= root_url %>",
      <% if meta_image %>
      "logo": "<%= meta_image %>"
      <% end %>
    <% end %>
  }
  </script>
<% end %>

app/views/layouts/_webfonts.html.erb
<%- config ||= {
  # google: {
  #   families: ['Open Sans:400,700,400italic,700italic'],
  # }
} -%>

<%- if config -%>
  <script>
    WebFontConfig = <%= raw config.to_json -%>;
    (function(d) {
      var wf = d.createElement('script'), s = d.scripts[0];
      wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js';
      s.parentNode.insertBefore(wf, s);
    })(document);
  </script>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">

    <%# Meta tags %>
    <meta charset="utf-8"/>
    <%= render "layouts/seo" -%>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <% unless Rails.env == "production" %>
      <meta name="robots" content="noindex,nofollow"/>
    <% end  %>
    <%= yield :meta %>

    <script>
      Ornament = window.Ornament || {};
      // dataLayer = window.dataLayer = {};
    </script>

    <%# Styles %>
    <%= stylesheet_pack_tag "application" %>
    <%= yield :styles %>

    <%# Scripts %>
    <script>
      var Ornicons = {
        chevronLeft: "<%= escape_javascript icon("chevron_left") %>",
        chevronRight: "<%= escape_javascript icon("chevron_right") %>",
        close: "<%= escape_javascript icon("close") %>"
      }
    </script>
    <%= javascript_pack_tag "application" %>
    <%= yield :scripts %>

    <%# Google Tag Manager - GTM-XXXXXXX %>
    <%- gtm_code = get_koi_site_setting("site.gtm_code") -%>
    <%- if gtm_code -%>
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','<%= gtm_code -%>');</script>
    <%- end -%>

    <%# Webfonts %>
    <%#= render "layouts/webfonts", config: {
      google: {
        families: ['Open Sans:400,700,400italic,700italic'],
      }
    } -%>

    <%# Koi Scripts %>
    <%- koi_scripts = get_koi_site_setting("site.head_scripts") -%>
    <%= koi_scripts if koi_scripts -%>

  </head>

  <body class="<%= yield :body_class -%>"> 

    <%- if gtm_code -%>
      <%# Google Tag Manager (noscript Version) %>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= gtm_code -%>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <%- end -%>

    <a class="skip-link" href="#main">skip to content</a>

    <div class="layout" data-tray-scroll-positioner id="top">

      <header class="header" role="banner">
        <div class="layout--container">
          <%= link_to root_path, class: "header--logo" do %>
            Header
          <% end %>
          <button class="header--menu" aria-label="Toggle menu" data-tray-button>
            <%= icon("hamburger", fill: "#ffffff", width: 25, height: 23) -%>
          </button>
        </div>
      </header>

      <div class="navigation navigation__primary">
        <div class="layout--container">
          <nav aria-label="Desktop Navigation">
            <%#= koi_render_navigation 'header_nav', 'header_navigation', renderer: :ornament_menu, level: 1..2, expand_all: true, dom_class: '' %>
          </nav>
        </div>
      </div>

      <%# Tray Navigation%>
      <div data-tray-overlay>
        <button data-tray-close title="Close menu">Close</button>
        <nav aria-label="Global Navigation">
          <div data-drilldown data-drilldown-merge>
            <%#= koi_render_navigation 'header_nav', 'header_navigation', renderer: :sf_menu, level: 1..4, expand_all: true, dom_class: '' %>
          </div>
        </nav>
      </div>

      <%# Content area that gets dark when overlay is open %>
      <div data-tray-overlay-darken class="layout--content">

        <%= render "/shared/oldie" -%>
        <%= render "/shared/flash" -%>
        <%= yield :above_layout %>

        <div class="layout--page environment-<%= Rails.env -%>">

          <%
            has_sidebar = content_for?(:sidebar)
            is_reversed = content_for?(:sidebar_right) || content_for?(:page_reversed)
            is_fullwidth = content_for?(:page_fullwidth)
            has_page_title = content_for?(:meta_title) || content_for?(:title)
            
            page_class = "page"
            page_class += " page__with-sidebar" if has_sidebar
            page_class += " page__reversed" if is_reversed

            container_class = ""
            container_class += " layout--main layout--container" unless is_fullwidth
          %>

          <div class="<%= container_class %>">
            <div class="<%= page_class %>">
              <% if has_sidebar %>
                <div class="page--sidebar">
                  <%= yield :sidebar %>
                </div>
              <% end %>
              <main class="page--main <%= yield(:layout_class) -%>" role="main" id="main">
                <% if has_page_title %>
                  <h1 class="heading-one page--title">
                    <% if content_for? :title %>
                      <%= yield :title %>
                    <% elsif content_for? :meta_title %>
                      <%= yield :meta_title %>
                    <% end %>
                  </h1>
                <% end %>
                <% if content_for?(:global) || !yield.blank? %>
                  <%= content_for?(:global) ? yield(:global) : yield %>
                <% end %>
              </main>
            </div>
          </div>
        </div>

        <%= yield :below_layout -%>
        <footer class="footer" role="contentinfo">
          <div class="layout--container">
            &copy <%= Time.now.year %>
          </div>
        </footer>
      </div>

    </div>

    <%= react_component "AjaxModal" %>

    <%= yield :scripts_bottom %>
    
    <%= render "layouts/analytics" -%>

  </body>

</html>

app/views/layouts/modal.html.erb
<%
  modal_title = ""
  modal_title = yield :title if content_for? :title
  modal_title = yield :page_title if content_for? :page_title
%>

<div class="lightbox--header">
  <div class="lightbox--title">
    <%= modal_title %>
  </div>
  <button class="lightbox--close" data-modal-close aria-label="Close modal">&times;</button>
</div>
<div class="lightbox--body panel--padding">
  <%= yield %>
</div>